version: "3"
services:
  v2ray1:
    image: v2ray/official
    restart: always
    command: v2ray -config=/etc/v2ray/config.json
    ports:
      - "9002:16823"
    volumes:
      - ./config.json:/etc/v2ray/config.json
  v2ray2:
    image: v2ray/official
    restart: always
    command: v2ray -config=/etc/v2ray/config.json
    ports:
      - "9003:16823"
    volumes:
      - ./config.json:/etc/v2ray/config.json