version: "3"
services:
  v2ray1:
    image: v2ray/official
    restart: always
    command: v2ray -config=/etc/v2ray/config.json
    ports:
      - "660:16823"
    volumes:
      - ./config.json:/etc/v2ray/config.json
  v2ray2:
    image: v2ray/official
    restart: always
    command: v2ray -config=/etc/v2ray/config.json
    ports:
      - "661:16823"
    volumes:
      - ./config.json:/etc/v2ray/config.json
  v2ray3:
    image: v2ray/official
    restart: always
    command: v2ray -config=/etc/v2ray/config.json
    ports:
      - "662:16823"
    volumes:
      - ./config.json:/etc/v2ray/config.json
  v2ray4:
    image: v2ray/official
    restart: always
    command: v2ray -config=/etc/v2ray/config.json
    ports:
      - "663:16823"
    volumes:
      - ./config.json:/etc/v2ray/config.json
  v2ray5:
    image: v2ray/official
    restart: always
    command: v2ray -config=/etc/v2ray/config.json
    ports:
      - "664:16823"
    volumes:
      - ./config.json:/etc/v2ray/config.json
  v2ray6:
    image: v2ray/official
    restart: always
    command: v2ray -config=/etc/v2ray/config.json
    ports:
      - "665:16823"
    volumes:
      - ./config.json:/etc/v2ray/config.json
  v2ray7:
    image: v2ray/official
    restart: always
    command: v2ray -config=/etc/v2ray/config.json
    ports:
      - "666:16823"
    volumes:
      - ./config.json:/etc/v2ray/config.json
  v2ray8:
    image: v2ray/official
    restart: always
    command: v2ray -config=/etc/v2ray/config.json
    ports:
      - "667:16823"
    volumes:
      - ./config.json:/etc/v2ray/config.json
  v2ray9:
    image: v2ray/official
    restart: always
    command: v2ray -config=/etc/v2ray/config.json
    ports:
      - "668:16823"
    volumes:
      - ./config.json:/etc/v2ray/config.json
  v2ray10:
    image: v2ray/official
    restart: always
    command: v2ray -config=/etc/v2ray/config.json
    ports:
      - "669:16823"
    volumes:
      - ./config.json:/etc/v2ray/config.json